### ISSUE TITLE
Getting started template deployment failure

### ISSUE THREAD

**Issue by jminty-liverton** [aws-solutions/aws-virtual-waiting-room#137]
**Describe the bug**
Cloud formation deployment of the 'getting started' template fails as the API gateway deployment cannot be setup without an API Gateway/Cloud Watch role ARN.

"CloudWatch Logs role ARN must be set in account settings to enable logging"

Resource error: 

**To Reproduce**
1) Download getting started template
2) Deploy to cloud formation

**Expected behavior**
1) Successful deployment of the resources

**Screenshots**

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/86443992/160953059-6ec4bbe8-feb1-42a1-8183-21f1b90b1a5c.png">

**Additional context**
- Attempted to deploy the solution to multiple regions with the same error

**Comment by JimTharioAmazon** [comment]
Hi, I'm assuming installing [aws-virtual-waiting-room-api-gateway-cw-logs-role.template](https://solutions-reference.s3.amazonaws.com/aws-virtual-waiting-room/latest/aws-virtual-waiting-room-api-gateway-cw-logs-role.template) fixed the problem for you. If not, please re-open.

**Comment by jminty-liverton** [comment]
@JimTharioAmazon  Correct, amazing what happens when you read the instructions :)
