### ISSUE TITLE
Ability to configure number of concurrent users allowed per event before waiting room is enabled - P1

### ISSUE THREAD

**Issue by jilladams** [aws-solutions/aws-virtual-waiting-room#17]
Ability to configure number of concurrent users allowed per event before waiting room is enabled - P1

Automatic activation of the waiting room based on high/low watermarks of users in the event site.

This would involve the integration between the event site and the inlet strategy code.

**Comment by JimTharioAmazon** [comment]
The sample waiting room code includes an parameter called 'passThru' and when set to true, the waiting room will not wait for the user's button clicks to obtain a position in line and depart the waiting room.
